#define CONSOLE_STREAMER_BAUDRATE 115200
#define CONSOLE_STREAMER Serial
#define CONSOLE_NAME "Terminal"
#define LOGGING_LEVEL LOW_LEVEL
#define WEB_SERVICE_TASK_STACK_SIZE 16384
#define NOTIFICATION_STACK_SIZE 8192